name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress
        run: tar -zcvf trivy-batch.tar.gz trivy-batch LICENSE plugin.yaml README.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            trivy-batch.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
